In [2]:
import tensorflow as tf

x_data=[[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data=[[152.],[185.],[180.],[196.],[142.]]

X=tf.placeholder(tf.float32,shape=[None,3])
Y=tf.placeholder(tf.float32,shape=[None,1])
W=tf.Variable(tf.random_normal([3,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

hypothesis=tf.matmul(X,W)+b
cost=tf.reduce_mean(tf.square(hypothesis-Y))
gradient=tf.reduce_mean(X*(W*X+b-Y))*2

optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],feed_dict={X:x_data,Y:y_data})
    if step%10==0:
        print(step,"Cost: ",cost_val,"\nPrediction:\n",hy_val)
        

0 Cost:  71440.6 
Prediction:
 [[ -78.54424286]
 [-105.43261719]
 [ -98.28560638]
 [-105.82255554]
 [ -84.1894455 ]]
10 Cost:  34.9811 
Prediction:
 [[ 157.82035828]
 [ 178.70146179]
 [ 181.65505981]
 [ 199.02760315]
 [ 132.54211426]]
20 Cost:  34.1511 
Prediction:
 [[ 158.51374817]
 [ 179.57618713]
 [ 182.49546814]
 [ 199.94458008]
 [ 133.21810913]]
30 Cost:  33.9758 
Prediction:
 [[ 158.49409485]
 [ 179.59378052]
 [ 182.49142456]
 [ 199.94195557]
 [ 133.24029541]]
40 Cost:  33.8014 
Prediction:
 [[ 158.47235107]
 [ 179.60874939]
 [ 182.48484802]
 [ 199.93656921]
 [ 133.26048279]]
50 Cost:  33.628 
Prediction:
 [[ 158.45069885]
 [ 179.623703  ]
 [ 182.47831726]
 [ 199.93122864]
 [ 133.28062439]]
60 Cost:  33.4555 
Prediction:
 [[ 158.42904663]
 [ 179.63858032]
 [ 182.47174072]
 [ 199.92584229]
 [ 133.30067444]]
70 Cost:  33.284 
Prediction:
 [[ 158.40748596]
 [ 179.65342712]
 [ 182.46522522]
 [ 199.92048645]
 [ 133.32067871]]
80 Cost:  33.1134 
Prediction:
 [[ 158.38598633]
 [ 179.668

910 Cost:  21.727 
Prediction:
 [[ 156.79196167]
 [ 180.76620483]
 [ 181.97689819]
 [ 199.51522827]
 [ 134.8249054 ]]
920 Cost:  21.6186 
Prediction:
 [[ 156.77488708]
 [ 180.7779541 ]
 [ 181.97174072]
 [ 199.51089478]
 [ 134.84085083]]
930 Cost:  21.5106 
Prediction:
 [[ 156.75785828]
 [ 180.78970337]
 [ 181.96661377]
 [ 199.50656128]
 [ 134.85678101]]
940 Cost:  21.4032 
Prediction:
 [[ 156.74087524]
 [ 180.80140686]
 [ 181.96147156]
 [ 199.50224304]
 [ 134.87266541]]
950 Cost:  21.2965 
Prediction:
 [[ 156.72393799]
 [ 180.81307983]
 [ 181.95637512]
 [ 199.49794006]
 [ 134.88848877]]
960 Cost:  21.1903 
Prediction:
 [[ 156.70704651]
 [ 180.82472229]
 [ 181.95127869]
 [ 199.49363708]
 [ 134.90428162]]
970 Cost:  21.0847 
Prediction:
 [[ 156.69021606]
 [ 180.83631897]
 [ 181.94619751]
 [ 199.48934937]
 [ 134.92002869]]
980 Cost:  20.9797 
Prediction:
 [[ 156.6734314 ]
 [ 180.84790039]
 [ 181.94113159]
 [ 199.48509216]
 [ 134.93574524]]
990 Cost:  20.8752 
Prediction:
 [[ 156.65667725]

 [[ 155.42895508]
 [ 181.70611572]
 [ 181.56626892]
 [ 199.16369629]
 [ 136.10438538]]
1820 Cost:  13.8987 
Prediction:
 [[ 155.41563416]
 [ 181.71530151]
 [ 181.56227112]
 [ 199.16020203]
 [ 136.11695862]]
1830 Cost:  13.8321 
Prediction:
 [[ 155.40234375]
 [ 181.7244873 ]
 [ 181.55828857]
 [ 199.15670776]
 [ 136.1295166 ]]
1840 Cost:  13.766 
Prediction:
 [[ 155.38908386]
 [ 181.73361206]
 [ 181.55429077]
 [ 199.15322876]
 [ 136.14199829]]
1850 Cost:  13.7002 
Prediction:
 [[ 155.37586975]
 [ 181.74273682]
 [ 181.55030823]
 [ 199.1497345 ]
 [ 136.15446472]]
1860 Cost:  13.6347 
Prediction:
 [[ 155.36270142]
 [ 181.75186157]
 [ 181.54637146]
 [ 199.14630127]
 [ 136.16693115]]
1870 Cost:  13.5696 
Prediction:
 [[ 155.34954834]
 [ 181.76092529]
 [ 181.54241943]
 [ 199.14283752]
 [ 136.17932129]]
1880 Cost:  13.5048 
Prediction:
 [[ 155.33644104]
 [ 181.76994324]
 [ 181.53846741]
 [ 199.13938904]
 [ 136.19169617]]
1890 Cost:  13.4404 
Prediction:
 [[ 155.32337952]
 [ 181.77896118]
 [ 181