In [1]:
import tensorflow as tf

filename_queue=tf.train.string_input_producer(
    ['data-01-test-score.csv'],shuffle=False,name='filename_queue')

reader=tf.TextLineReader()
key,value=reader.read(filename_queue)

record_defaults=[[0.],[0.],[0.],[0.]]
xy=tf.decode_csv(value,record_defaults=record_defaults)

train_x_batch,train_y_batch= tf.train.batch([xy[0:-1],xy[-1:]],batch_size=10)

In [2]:

X=tf.placeholder(tf.float32,shape=[None,3])
Y=tf.placeholder(tf.float32,shape=[None,1])

W=tf.Variable(tf.random_normal([3,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

hypothesis=tf.matmul(X,W)+b
cost=tf.reduce_mean(tf.square(hypothesis-Y))

optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)


In [3]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

coord=tf.train.Coordinator()
threads=tf.train.start_queue_runners(sess=sess,coord=coord)

for step in range(2001):
    x_batch,y_batch=sess.run([train_x_batch,train_y_batch])
    cost_val,hy_val,_=sess.run([cost,hypothesis,train],feed_dict={X:x_batch,Y:y_batch})
    if step % 10 ==0:
        print(step,"Cost: ", cost_val, "\nPrediction: \n", hy_val)
        
print(x_batch)
print(y_batch)

print(sess.run(hypothesis,feed_dict={X:[[100,70,101]]}))
print(sess.run(hypothesis,feed_dict={X:[[60,70,110],[90,100,80]]}))

coord.request_stop()
coord.join(threads)

0 Cost:  12669.1 
Prediction: 
 [[ 258.16537476]
 [ 302.21331787]
 [ 301.87805176]
 [ 328.12747192]
 [ 229.25744629]
 [ 167.5854187 ]
 [ 258.16537476]
 [ 302.21331787]
 [ 301.87805176]
 [ 328.12747192]]
10 Cost:  15.5131 
Prediction: 
 [[ 137.20788574]
 [  99.73477173]
 [ 157.75292969]
 [ 181.52761841]
 [ 182.96328735]
 [ 198.62908936]
 [ 137.20788574]
 [  99.73477173]
 [ 157.75292969]
 [ 181.52761841]]
20 Cost:  12.2889 
Prediction: 
 [[ 182.49949646]
 [ 198.12591553]
 [ 136.865448  ]
 [  99.48856354]
 [ 157.35037231]
 [ 181.07162476]
 [ 182.49949646]
 [ 198.12591553]
 [ 136.865448  ]
 [  99.48856354]]
30 Cost:  13.7258 
Prediction: 
 [[ 157.31159973]
 [ 181.05224609]
 [ 182.46621704]
 [ 198.09150696]
 [ 136.85594177]
 [  99.48757935]
 [ 157.31159973]
 [ 181.05224609]
 [ 182.46621704]
 [ 198.09150696]]
40 Cost:  15.7421 
Prediction: 
 [[ 136.65722656]
 [  99.34722137]
 [ 157.06632996]
 [ 180.78483582]
 [ 182.1884613 ]
 [ 197.79092407]
 [ 136.65722656]
 [  99.34722137]
 [ 157.06632996]

480 Cost:  10.8189 
Prediction: 
 [[ 156.62368774]
 [ 181.37614441]
 [ 182.1860199 ]
 [ 197.86221313]
 [ 137.32666016]
 [ 100.08653259]
 [ 156.62368774]
 [ 181.37614441]
 [ 182.1860199 ]
 [ 197.86221313]]
490 Cost:  12.4042 
Prediction: 
 [[ 137.15870667]
 [  99.96782684]
 [ 156.415802  ]
 [ 181.14987183]
 [ 181.95079041]
 [ 197.60757446]
 [ 137.15870667]
 [  99.96782684]
 [ 156.415802  ]
 [ 181.14987183]]
500 Cost:  9.53982 
Prediction: 
 [[ 182.20433044]
 [ 197.88520813]
 [ 137.36933899]
 [ 100.12827301]
 [ 156.6204834 ]
 [ 181.4198761 ]
 [ 182.20433044]
 [ 197.88520813]
 [ 137.36933899]
 [ 100.12827301]]
510 Cost:  10.653 
Prediction: 
 [[ 156.58139038]
 [ 181.39605713]
 [ 182.16880798]
 [ 197.84796143]
 [ 137.35575867]
 [ 100.12320709]
 [ 156.58139038]
 [ 181.39605713]
 [ 182.16880798]
 [ 197.84796143]]
520 Cost:  12.2149 
Prediction: 
 [[ 137.18968201]
 [ 100.00585175]
 [ 156.37580872]
 [ 181.17233276]
 [ 181.93618774]
 [ 197.59616089]
 [ 137.18968201]
 [ 100.00585175]
 [ 156.3758

970 Cost:  9.77824 
Prediction: 
 [[ 137.62191772]
 [ 100.53068542]
 [ 155.82200623]
 [ 181.48445129]
 [ 181.73490906]
 [ 197.43635559]
 [ 137.62191772]
 [ 100.53068542]
 [ 155.82200623]
 [ 181.48445129]]
980 Cost:  7.54623 
Prediction: 
 [[ 181.95851135]
 [ 197.68106079]
 [ 137.80734253]
 [ 100.67158508]
 [ 156.0027771 ]
 [ 181.72216797]
 [ 181.95851135]
 [ 197.68106079]
 [ 137.80734253]
 [ 100.67158508]]
990 Cost:  8.38385 
Prediction: 
 [[ 155.95968628]
 [ 181.69012451]
 [ 181.91668701]
 [ 197.63659668]
 [ 137.78689575]
 [ 100.66056061]
 [ 155.95968628]
 [ 181.69012451]
 [ 181.91668701]
 [ 197.63659668]]
1000 Cost:  9.63986 
Prediction: 
 [[ 137.64866638]
 [ 100.56281281]
 [ 155.78797913]
 [ 181.50367737]
 [ 181.72259521]
 [ 197.42640686]
 [ 137.64866638]
 [ 100.56281281]
 [ 155.78797913]
 [ 181.50367737]]
1010 Cost:  7.4416 
Prediction: 
 [[ 181.94445801]
 [ 197.66920471]
 [ 137.83262634]
 [ 100.70259094]
 [ 155.96737671]
 [ 181.73953247]
 [ 181.94445801]
 [ 197.66920471]
 [ 137.83

1410 Cost:  6.88648 
Prediction: 
 [[ 155.49201965]
 [ 181.91238403]
 [ 181.7278595 ]
 [ 197.47431946]
 [ 138.11572266]
 [ 101.06163788]
 [ 155.49201965]
 [ 181.91238403]
 [ 181.7278595 ]
 [ 197.47431946]]
1420 Cost:  7.96073 
Prediction: 
 [[ 137.99848938]
 [ 100.97870636]
 [ 155.34580994]
 [ 181.75402832]
 [ 181.56280518]
 [ 197.29548645]
 [ 137.99848938]
 [ 100.97870636]
 [ 155.34580994]
 [ 181.75402832]]
1430 Cost:  6.17594 
Prediction: 
 [[ 181.76220703]
 [ 197.5135498 ]
 [ 138.16351318]
 [ 101.10384369]
 [ 155.50726318]
 [ 181.96565247]
 [ 181.76220703]
 [ 197.5135498 ]
 [ 138.16351318]
 [ 101.10384369]]
1440 Cost:  6.79372 
Prediction: 
 [[ 155.46107483]
 [ 181.92713928]
 [ 181.71540833]
 [ 197.4634552 ]
 [ 138.13764954]
 [ 101.08808136]
 [ 155.46107483]
 [ 181.92713928]
 [ 181.71540833]
 [ 197.4634552 ]]
1450 Cost:  7.85739 
Prediction: 
 [[ 138.02182007]
 [ 101.00611115]
 [ 155.3165741 ]
 [ 181.77064514]
 [ 181.55227661]
 [ 197.28672791]
 [ 138.02182007]
 [ 101.00611115]
 [ 15

1890 Cost:  5.58923 
Prediction: 
 [[ 155.03234863]
 [ 182.13198853]
 [ 181.54321289]
 [ 197.31109619]
 [ 138.44395447]
 [ 101.45235443]
 [ 155.03234863]
 [ 182.13198853]
 [ 181.54321289]
 [ 197.31109619]]
1900 Cost:  6.52449 
Prediction: 
 [[ 138.34741211]
 [ 101.38400269]
 [ 154.9112854 ]
 [ 182.00134277]
 [ 181.40678406]
 [ 197.16322327]
 [ 138.34741211]
 [ 101.38400269]
 [ 154.9112854 ]
 [ 182.00134277]]
1910 Cost:  5.10111 
Prediction: 
 [[ 181.58390808]
 [ 197.35678101]
 [ 138.49371338]
 [ 101.49465942]
 [ 155.0549469 ]
 [ 182.18901062]
 [ 181.58390808]
 [ 197.35678101]
 [ 138.49371338]
 [ 101.49465942]]
1920 Cost:  5.5201 
Prediction: 
 [[ 155.0059967 ]
 [ 182.1446228 ]
 [ 181.53268433]
 [ 197.30162048]
 [ 138.46295166]
 [ 101.474617  ]
 [ 155.0059967 ]
 [ 182.1446228 ]
 [ 181.53268433]
 [ 197.30162048]]
1930 Cost:  6.44856 
Prediction: 
 [[ 138.36761475]
 [ 101.40711212]
 [ 154.88641357]
 [ 182.01557922]
 [ 181.39790344]
 [ 197.15553284]
 [ 138.36761475]
 [ 101.40711212]
 [ 154